import Head from "next/head";
import Sidebar from "../components/sidebar/Sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* Sidebar */}
        <Sidebar />

        {/* Feed */}

        {/* Widget */}

        {/* Modal */}
      </main>
    </>
  );
}
